### ISSUE TITLE
Mac のインストール手順がわかりにくい

### ISSUE THREAD

**Issue by ikesato** [SonyCSL/MoekadenRoom#2]
README.md
> 以下からお好きなものを落として使ってください。Win64以外はJavaが必要だと思います。また、Processing IDEから実行するにはlibrariesフォルダ内にOpenECHO for ProcessingとControlP5が必要です。OpenECHOはこちらから落としてください。ControlP5はv2.2.5で確認しました。

Mac の IDE で動かす場合、 [ここ](https://github.com/SonyCSL/OpenECHO/blob/master/Processing/libraries) にある controlP5.jar では動きませんでした。バージョンがあっていないのかもしれません。

以下の手順が必要でした。
1. Processing で MoekadenRoom.pde を開く
2. メニュー > スケッチ > ライブラリをインポート... > ライブラリを追加
3. テキストボックスに controlP5 を入力し "install" ボタンをクリックしインストール
version は 2.2.6 でした。
4. メニュー > スケッチ > ファイルを追加
5. 下のURLから OpenECHO.jar を直接ダウンロードし、ファイル選択ダイアログで jar ファイル指定
https://github.com/SonyCSL/OpenECHO/blob/master/Processing/libraries/OpenECHO/library/OpenECHO.jar
6. 再生をクリック
完了

環境
macOS Sierra 10.12.4
Processing 3.3.4
controlP5 2.2.6

**Comment by sowd** [comment]
今さらですがREADMEに頂いた情報を反映させました。どうもありがとうございました！
