### ISSUE TITLE
Can i get information such as current temperature value of air conditioner MoekadenRoom?

### ISSUE THREAD

**Issue by hoangl-hle** [SonyCSL/MoekadenRoom#4]
Can i get information such as current temperature value of air conditioner MoekadenRoom? And How can i get it. Does the home air conditioner in the MoekadenRomm have full functionality specified in class HomeAirConditioner.java. ThanksThanks @sowd

**Comment by sowd** [comment]
MoekadenRoom is an ECHONET Lite emulator of various appliances.
Yes, you can obtain information through ECHONET Lite protocol.

ECHONET Lite has mandatory and optional properties. MoekadenRoom implements only mandatory properties. See the spec:

https://echonet.jp/spec-en/

**Comment by hoangle98** [comment]
@sowd  I am using ` protected void onGetSetTemperatureValue(EchoObject eoj, short tid, byte esv, EchoProperty property, boolean success) {}` to receive res from req `device.get().reqGetSetTemperatureValue().send()` but but no response is received. As i has read from [https://echonet.jp/wp/wp-content/uploads/pdf/General/Standard/Echonet/Version_2_11_en/spec_v211e_Appendix.pdf](url)  set Temperature Value EPC 0xB3 Access/Rule Get/Set is mandatory and in class HomeAirConditioner of lib OpenEcho:
/**
                     * Property name : Set temperature value<br>
                     * <br>
                     * EPC : 0xB3<br>
                     * <br>
                     * Contents of property :<br>
                     * Used to set the temperature and to<br>
                     * acquire the current setting.<br>
                     * <br>
                     * Value range (decimal notation) :<br>
                     * 0x00.0x32 (0.50.C)<br>
                     * <br>
                     * Data type : unsigned char<br>
                     * <br>
                     * Data size : 1 byte<br>
                     * <br>
                     * Unit : .C<br>
                     * <br>
                     * Access rule :<br>
                     * Announce - undefined<br>
                     * Set - mandatory<br>
                     * Get - mandatory<br>
                    protected void onGetSetTemperatureValue(EchoObject eoj, short tid, byte esv, EchoProperty property, boolean success) {}
                    **/
and in MoekadenRoom.java
`
  protected byte[] getSetTemperatureValue() {  return mTemperature;}

  // \u3088\u308a\u64cd\u4f5c\u3057\u3084\u3059\u3044\u95a2\u6570\u3092\u4f5c\u3063\u3066\u307f\u307e\u3057\u305f\u3002
  // \u203bHomeAirConditioner\u304b\u3089\u306e\u30aa\u30fc\u30d0\u30fc\u30e9\u30a4\u30c9\u3067\u306f\u3042\u308a\u307e\u305b\u3093\u3002
  protected void setTemperatureValueInt(int temp) {
    try{
      this.set().reqSetSetTemperatureValue(new byte[]{(byte)temp}).send();
    } catch(IOException e){
      e.printStackTrace();
    }
  }`
Please help me to receive current temperature of AC. Thank you so much.

**Comment by hoangl-hle** [comment]
Thank you so much and sorry for bothering you.
