### ISSUE TITLE
スマートメーターの積算電力量が取得できません

### ISSUE THREAD

**Issue by moscow4gh** [SonyCSL/MoekadenRoom#5]
スマートメーター(DEOJ=0x028801)から積算電力量(EPC=0xe0)または30分毎の最新積算電力量(EPC=0xea)をGetするとGet_SNAが応答されます。
ほかのプロパティは正常にGet_Resが応答されます。
履歴のように何か手順がありますでしょうか？

**Comment by moscow4gh** [comment]
Pull requestするのが正しいのかもしれませんが、修正した差分を添付します
[modified.txt](https://github.com/SonyCSL/MoekadenRoom/files/3786877/modified.txt)

**Comment by sowd** [comment]
一年以上も放置してしまい、誠に申し訳ありません。気づかずでして…
頂いたコメントを今反映させました。
